### ISSUE TITLE
Misaligned charts

### ISSUE THREAD

**Issue by inorganik** [MAKIO135/console.chart#3]
Hey there, I really like your project. I've seen some strange behavior so I wanted to let you know about it. I started using it in one of my own open source projects, [Dogebot](https://github.com/inorganik/dogebot). It's a silly thing, that auto-mines dogecoin at the dogecoin simulator [dogecoin.se](dogecoin.se). 

It's kind of addicting and it was fun to make a script that auto-mines dogecoin. When I found your lib I was excited because I could use it to show progress. For instance some things it tracks is your coins/second every minute. The user can chart these values by typing in the console `console.chart(coinsPerSecLastHour)` for example.

The game deals with some incredibly large values, and I noticed some misalignment as I was logging charts:

![wonky charts](https://i.stack.imgur.com/obZXe.png)

**Comment by MAKIO135** [comment]
Same as for #2, except you seem to be using a non monospace font which causes a problem for aligning leading white spaces. console.chart should use only monospace fonts since computing font width would heavily augment its weight.
